id = "wpilib"
name = "Java WPILIB"
version = "0.1.0"
schema_version = 1
authors = [
    "Valentine Briese <valentinegb@icloud.com>",
    "Samuser107 L.Longheval <samuser107@gmail.com>",
    "Yury Abykhodau <abehodau@gmail.com>",
    "Gavin Ostler <gvnostler@gmail.com>",
]
description = "Java support."
repository = "https://github.com/gavinostler/java-jdtls-wpilib"

[grammars.java]
repository = "https://github.com/tree-sitter/tree-sitter-java"
commit = "94703d5a6bed02b98e438d7cad1136c01a60ba2c"

[language_servers.wpilib]
name = "Eclipse JDT Language Server (WPILIB)"
languages = ["Java"]
